version: 0.2

phases:
  pre_build:
    commands:
      - echo "pre build stuff"
  build:
    commands:
      - docker pull coala/base:latest
      - docker build --cache-from coala/base:latest -t testimage:v.0.0.1 .
  post_build:
    commands:
      - docker images