version: 0.2

phases:
  pre_build:
    commands:
      - docker images
  build:
    commands:
      - docker build -t testimage:v.0.0.1 .
  post_build:
    commands:
      - echo Check if docker storage is on EFS...
      - docker images
cache:
  paths:
    - '/var/lib/docker/**/*'