version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t testimage:v.0.0.1 .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Sync Docker storage to s3...
      - ls /var/lib/docker/
      - sudo ls /var/lib/docker
      #- aws s3 sync /var/lib/docker/aufs s3://wesblake-codebuild-cache/  
