version: 0.2

phases:
  pre_build:
    commands:
      - ps aux | grep docker
      - mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 fs-9551addd.efs.us-east-1.amazonaws.com:/ /efs
  build:
    commands:
      - docker build -t testimage:v.0.0.1 .
  post_build:
    commands:
      - echo Check if docker storage is on EFS...
      - ls -al /efs