version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      #- aws s3 cp s3://wesblake-codebuild-cache/docker-local.tar.gz /tmp/
      #- tar -zxvf /tmp/docker-local.tar.gz /var/lib/docker
      - ls -al /var/lib/docker/overlay
      - docker images
  build:
    commands:
      - echo Building the Docker image...          
      - ls -al /var/lib/docker/overlay/
      - docker images
      - docker build -t testimage:v.0.0.1 .
  post_build:
    commands:
      - echo Sync Docker storage to s3...
      - tar -zcvf /tmp/docker-local.tar.gz /var/lib/docker
      - aws s3 cp /tmp/docker-local.tar.gz s3://wesblake-codebuild-cache/  
