version: 0.2

phases:
  pre_build:
    commands:
      - echo 'mount EFS'...
      - mdkir /efs
      - apt-get update
      - apt-get install -y nfs-common
      - mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 fs-9551addd.efs.us-east-1.amazonaws.com:/ /efs
      - ln -s /efs /var/lib/docker
  build:
    commands:
      - echo 'Building the Docker image'...          
      - docker images
      - docker build -t testimage:v.0.0.1 .
  post_build:
    commands:
      - echo Check if docker storage is on EFS...
      - ls -al /efs