version: 0.2

phases:
  pre_build:
    commands:
      - ls -al /efs
      #- pkill -f dockerd
      #- rm -rf /var/run/docker.pid
      #- /bin/sh $CODEBUILD_SRC_DIR/dockerd-entrypoint.sh while [ ! -f /codebuild/readonly/bin/executor.done ]; do sleep 1; done && /codebuild/readonly/bin/executor
  build:
    commands:
      - ps aux | grep docker
      - docker build -t testimage:v.0.0.1 .
  post_build:
    commands:
      - echo Check if docker storage is on EFS...
      - ls -al /efs